[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Bio"
authors = [{name = "Kevin Egedy", email = "kegedy@gmail.com"}]
dynamic = ["version", "description"]
